.TH GRML-TIPS 1
.SH NAME
grml-tips \- query a signature file for a specific keyword and display results
.SH SYNOPSIS
.B grml-tips
.RI " keyword"
.SH DESCRIPTION
This manual page documents briefly the
.B grml-tips
command.
.PP
.SH Usage example
.TP
.BR "grml-tips ntfs"
Query grml-tips file for tips / hints including keyword "ntfs".
.TP
.BR "grml-tips ."
Display all available grml-tips at once.
.SH FILES
.PP
/usr/share/grml-tips/grml_tips
.PP
Signature file containing the tips.
.SH NOTES
By default grml-tips uses agrep for searching through the signature file.
If agrep is not available it falls back to use of awk.
.SH OPTIONS
This program does not support any options.
.SH SEE ALSO
.BR grml (1)
.SH AUTHOR
grml-tips was written by Michael Prokop <mika@grml.org>
.PP
This manual page was written by Michael Prokop <mika@grml.org>
for the grml project (but may be used by others).
