.TH GRML-TIPS 1 "Dezember 11, 2005"
.SH NAME
grml-tips \- query a signature file for a specific keyword and display results
.SH SYNOPSIS
.B grml-tips
.RI " keyword"
.SH DESCRIPTION
This manual page documents briefly the
.B grml-tips
command.
.PP
.SH Usage example
.PP
grml-tips ntfs
.PP
Query grml-tips file for tips / hints including keyword "ntfs".
.SH FILES
.PP
/etc/grml/grml_tips
.PP
Signature file with tips.
.SH OPTIONS
This program does not support any options.
.SH SEE ALSO
.BR grml (1)
.SH AUTHOR
grml-tips was written by Michael Prokop <mika@grml.org>
.PP
This manual page was written by Michael Prokop <mika@grml.org>,
for the grml project (but may be used by others).
