#!/bin/sh -e

if [ -x /usr/lib/grml-tips/grml-tips-tags ]
then
	echo -n "Generating grml-tips tag database: "
	if /usr/lib/grml-tips/grml-tips-tags
	then
		echo "Ok"
	else
		echo "Failed"
	fi
fi

 #DEBHELPER#
 exit 0
